### PR TITLE
Fixed redirectURI

### PR DESCRIPTION
**Pull request by surajnarwade**
reference #1019

### CODE REVIEW

**Comment by sbose78** [comment]
The reference is incorrect :) 
This fixes 'unable to connect github account'.

The one referenced above was 'unable to login via openshift-v3'

**Comment by sbose78** [comment]
Looks good for merge.
( for github login/connect issue from 'Getting started' page. )

**Comment by rawlingsj** [comment]
[merge]

**Comment by rawlingsj** [comment]
thanks!

**Pull request merged**
