### PR TITLE
Update pom property fabric8.maven.plugin.version to 3.2.16

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
[merge] lgtm

**Comment by rhuss** [comment]
The merge works (which is only a version upgrade on fmp), but the app-catalog fails with tons of those errors which does not _seem_ to be related to the f-m-p upgrade:

```
[INFO] 
[INFO] --- fabric8-maven-plugin:3.2.16:resource (fmp) @ app-catalog ---
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[INFO] F8: Running in Kubernetes mode
2017-02-02 08:31:39,430 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
Logging Provider: org.jboss.logging.Log4j2LoggerProvider
HV000001: Hibernate Validator 5.2.4.Final
Found javax.persistence.Persistence on classpath containing 'getPersistenceUtil'. Assuming JPA 2 environment. Trying to instantiate JPA aware TraversableResolver
Instantiated JPA aware TraversableResolver of type org.hibernate.validator.internal.engine.resolver.JPATraversableResolver.
Trying to load META-INF/validation.xml for XML based Validator configuration.
Trying to load META-INF/validation.xml via TCCL
Trying to load META-INF/validation.xml via Hibernate Validator's class loader
No META-INF/validation.xml found. Using annotation based configuration only.
HV000188: Parameterized type with more than one argument is not supported: java.util.LinkedHashMap.java.util.LinkedHashMap$Entry<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.LinkedHashMap.java.util.LinkedHashMap$Entry<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiFunction<? super K, ? super V, ? extends V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiConsumer<? super K, ? super V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$TreeNode<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$TreeNode<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.HashMap.java.util.HashMap$Node<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.Map.java.util.Map$Entry<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.LinkedHashMap.java.util.LinkedHashMap$Entry<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.LinkedHashMap.java.util.LinkedHashMap$Entry<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.LinkedHashMap.java.util.LinkedHashMap$Entry<K, V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiFunction<? super K, ? super V, ? extends V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiConsumer<? super K, ? super V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.Function<? super K, ? extends V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiFunction<? super K, ? super V, ? extends V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiFunction<? super K, ? super V, ? extends V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiFunction<? super V, ? super V, ? extends V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiFunction<? super K, ? super V, ? extends V>
HV000188: Parameterized type with more than one argument is not supported: java.util.function.BiConsumer<? super K, ? super V>
```

@jstrachan @rawlingsj : Any idea why hibernate validator fails here ? Could it be because of

```
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
```

?

I tried it with 3.2.15 (the current version) of f-m-p and its doesn't work either (fails with the same error).

**Comment by rhuss** [comment]
Same also for 3.2.14

**Comment by rhuss** [comment]
Ok, the reason is not that error nor the validation errors.

The main problem is that all dependencies are declared as plugin dependencies, not as regular dependencies. This means, when one of these dependencies e.g. references a different kubernetes-model then the plugin itself, nasty "MethodNotFoundException" occur. The solution is to move it outside of the plugin definition to regular dependencies. Then it works smoothly and also these awful Hibernate validator warnings vanish.

@jstrachan @rawlingsj can we change this to a regular dependencies in "app-catalog" ? The net effect should be the same since the dependency enricher picks up the dependencies from the plugin **and** from the project. 

would be awesome if you could give some quick feedback, otherwise the whole release pipeline is blocked.

**Comment by rawlingsj** [comment]
@rhuss I'm travelling at the moment with barely any wifi.  If that's the fix then feel free to add it in.  I've copied the steps from slack to use, if you resolve the issue as you described and push to the branch below the pipeline will continue when the PR merges...

Hope that helps, if not I can look first thing as it's a late return home for me tonight.

```
git clone git@github.com:fabric8io/fabric8-platform.git
cd fabric8-platform
git fetch origin pull/140/head:fixPR140
git checkout fixPR140

  [resolve issue]

git commit -a -m 'resolved merge issues caused by release dependency updates'
git push origin fixPR140:versionUpdate4443de7a-5381-4c07-9a4b-e986ef3a9cf4
```

**Comment by rhuss** [comment]
@rawlingsj let me try that. Hopefully the pipeline will succeed, will let you know when its done.


Safe travels !

**Comment by rawlingsj** [comment]
Ok - I've got my fingers crossed that it works!

**Comment by rhuss** [comment]
[merge]

**Comment by rawlingsj** [comment]
[merge]

**Comment by rawlingsj** [comment]
@rhuss we'll figure out the whitelist in the morning.  Your fix looks to have sorted the CI though - yay!

**Pull request merged**
