### PR TITLE
Revert: Fixed pom dependencies by moving them out of plug dependency section - and added a better solution that doesn't add all the optional apps in the catalog into the fabric8-platform along with a ton of duplicate resources

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by jstrachan** [comment]
[merge]

**Comment by rhuss** [comment]
@jstrachan I'm just about to look into the duplicate init-container issues with this double enrichment problem. Where did it occur for you ?

W.r.t to the revert here, why does a direct dependency does not work ? 

I ask, because its likely that there will be a clash if one of the mentioned dependencies refers to a library the fabric8-maven-plugin uses, too, but with a different version. Then the dependencies' dependendcy overrides the original plugin's dependency (as it seems) causing method-signature mismatch errors and the like. This wont happen if we do not mess with the plugin's dependency, but use "normal" deps, maybe with a scope of `provided` to avoid adding them as transitive (if this is needed).

**Comment by jstrachan** [comment]
@rhuss to see the duplicate init-container, try build any of the packages in the fabric8-platform project - e.g. cd-pipeline is a nice simple-ish one.
https://github.com/fabric8io/fabric8-platform/tree/master/packages/cd-pipeline

You'll see those warnings appear because the init container enricher gets triggered 2 more times; despite the gogs Deployment already being created and imported as a dependency.

On the revert; the issue is that we have mandatory apps (e.g. when you install fabric8-platform you get jenkins) and optional apps (elasticsearch, chat etc that users choose to install later via the `Run...`button). 

The optional apps are used in the app-catalog to create Template on openshift and ConfigMaps on kubernetes which show up in the `Run...` UI in fabric8. The reason they are plugin dependencies rather than real dependencies is to avoid mandatory transitive dependencies (thus removing the ability of things to be optional). So that when you depend on the `app-catalog` you don't want to force every single Deployment that a user could choose to run via the `Run....` UI - to be always run for everyone.

So to fix the issue I reverted your change and instead of depending recursively on everything; I just depended on the underlying kubernetes-api / kubernetes-client libraries - which are fine to be dependent on; they don't imply forcing a mandatory Deployment to be added inside the fabric8-platform package.

Incidentally the reason for the CI error we had was that transitive dependencies of the apps was bringing in some old dependencies of kubernetes-client / kubernetes-api - e.g. the kubeflix apps were causing the issues. By forcing recent versions of those in fabric8-platform we avoid this kinda thing going forward.

**Comment by rhuss** [comment]
@jstrachan The reason for the issue is simple as well as the fix: the `VolumeEnricher` comes after the `DependencyEnricher` and hence does the enricher again. And you are not using the dedicated `aggregate` profile which was introduced specific for the case of aggregating resource descriptors.

The fix would have been super simple and does not require any code change:

```
mvn -Dfabric8.profile=aggregate clean install
```

or better adding the property to the `<properties>` section. The pre-defined profile `aggregate` simply only runs the dependency enricher and no other enricher, which makes sense if you have only an aggregation project. 

Nevertheless I will make the VolumePermissionEnricher more robust (using a more descriptive name for the init container and do no adding it if already existing) and move the DependencyEnricher last.

BTW, you find all predefined profiles in https://github.com/fabric8io/fabric8-maven-plugin/blob/master/plugin/src/main/resources/META-INF/fabric8/profiles-default.yml

**Comment by rhuss** [comment]
and the documentation about the predefined profiles can be found here: https://maven.fabric8.io/#profiles-predefined

**Comment by jstrachan** [comment]
thanks for the heads up @rhuss

**Pull request merged**
